version: '3'

services:
  front-end:
    build: ./to_do_list
    container_name: front-end
    working_dir: /srv/front-end
    ports:
      - 3000:3000
    restart: always
    environment:
      - PORT_FRONT=3000
    # env_file:
    #   - ./.env
    # command: bash -c 'npm i && npm run dev'
    # networks:
    #   - daRoca
    volumes:
      - ./to_do_list/src:/srv/front-end/src