import { ContextProvider } from '@/context/context'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'To do List',
  description: 'Generated by create next app'
}

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}): React.JSX.Element {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <ContextProvider>
          {children}
        </ContextProvider>
        </body>
    </html>
  )
}
